'use strict';
const {app,ipcMain,BrowserWindow}=require('electron'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const output=path.resolve(process.env.Q1_OUTPUT||'qualification-runtime-output');fs.mkdirSync(output,{recursive:true});app.setPath('userData',path.join(output,'user-data'));app.setPath('sessionData',path.join(output,'session-data'));app.disableHardwareAcceleration();app.enableSandbox();
const results={platform:process.platform,electron:process.versions.electron,productionEligible:false,scope:'Packaged frozen C2 components + qualification provider, not whole VCPChat or production admission',tests:[]};let b;
const timer=setTimeout(()=>{fs.writeFileSync(path.join(output,'RUNTIME_TIMEOUT.json'),JSON.stringify(results));app.exit(2);},40000);
app.whenReady().then(async()=>{
 const expected=require('./artifact-native.json').sha256;const binary=fs.readFileSync(path.join(__dirname,'native/build/Release/qualification_provider.node'));assert.equal(crypto.createHash('sha256').update(binary).digest('hex'),expected,'NATIVE_ARTIFACT_MISMATCH');
 const {runNative}=require('./probe.cjs');results.native=await runNative(process.env.Q1_MODE||'TARGET',crypto.randomBytes(16).toString('hex'),{foreign:false});
 const root=path.join(__dirname,'frozen-c2');const {TrustedDecisionBoundary}=require(root+'/modules/trusted-client/trustedDecisionBoundary');const {projection}=require(root+'/modules/trusted-client/humanSafeCanonicalDisplay');
 b=new TrustedDecisionBoundary({BrowserWindow,projectRoot:root,invalidate:()=>{}});let calls=0;ipcMain.handle('trusted-approval:decision',(e,d)=>{assert.equal(e.sender,b.window.webContents);assert.equal(e.senderFrame,e.sender.mainFrame);assert.deepEqual(Object.keys(d).sort(),['decision','viewGeneration']);calls++;return {accepted:false};});
 await b.open();b.window.focus();const wc=b.window.webContents,p=wc.getLastWebPreferences();for(const key of ['sandbox','contextIsolation','webSecurity'])assert.equal(p[key],true);assert.equal(p.nodeIntegration,false);wc.openDevTools();await new Promise(r=>setTimeout(r,50));assert.equal(wc.isDevToolsOpened(),false);results.webPreferences=p;results.tests.push('sandbox/contextIsolation/webSecurity configured');
 const api=await wc.executeJavaScript('({keys:Object.keys(window.trustedApproval).sort(),node:typeof require,ordinary:typeof window.chatAPI})');assert.deepEqual(api,{keys:['onPresentAuthority','submitDecision'],node:'undefined',ordinary:'undefined'});results.tests.push('actual packaged preload narrow API');
 const target='<svg onload=alert(1)>\u202e/project\u200b';b.present({viewGeneration:'q1-test',...projection({toolName:'CodexWorker',args:{command:'grant',purpose:'propose',projectRoot:target}})});await new Promise(r=>setTimeout(r,150));
 const v=await wc.executeJavaScript('({svg:document.querySelectorAll("#fields svg").length,exact:[...document.querySelectorAll("#fields pre")].map(x=>x.textContent)})');assert.equal(v.svg,0);assert(v.exact.includes(target));results.tests.push('actual packaged inert exact target');fs.writeFileSync(path.join(output,'trusted-window.png'),(await wc.capturePage()).toPNG());
 await wc.executeJavaScript('window.trustedApproval.submitDecision({viewGeneration:"q1-test",decision:"DENY"})');assert.equal(calls,1);await wc.executeJavaScript('window.trustedApproval.submitDecision({viewGeneration:"q1-test",decision:"ALLOW",requestId:"forged"})');assert.equal(calls,1);results.tests.push('actual IPC rejects renderer request injection');
 const {HumanInputProvenance}=require(root+'/modules/trusted-client/humanInputProvenance');assert.equal(await new HumanInputProvenance().capture({decision:'ALLOW'}),null);results.HumanInputProvenance='UNPROVEN';results.syntheticInput='Automation for UI behavior only, not Human evidence';
 const {SecurityEpoch}=require(root+'/modules/trusted-client/securityEpoch');const epoch=new SecurityEpoch('TEST_ONLY');epoch.withdraw();epoch.closeOldIdentity();await assert.rejects(()=>epoch.verifyPathB(async()=>null));assert.equal(epoch.canAuthorize(),false);results.rollback={model:'FAIL_CLOSED_PASS',OS_rollback:'UNPROVEN',pathA:epoch.pathA()};
 results.result='PASS_BOUNDED_PACKAGED_COMPONENT_TESTS';fs.writeFileSync(path.join(output,'RUNTIME_REPORT.json'),JSON.stringify(results,null,2));clearTimeout(timer);b.destroy();app.exit(0);
}).catch(e=>{results.result='FAIL';results.error=e.stack;fs.writeFileSync(path.join(output,'RUNTIME_REPORT.json'),JSON.stringify(results,null,2));b?.destroy();app.exit(1);});
