'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createApprovalProtocol,ACK_WAIT_MS,SYNC_WAIT_MS}=require('../../modules/trusted-client/approvalDelivery');
const request=()=>({requestId:'one',protocolVersion:1,toolName:'CodexWorker',args:{command:'grant',projectRoot:'/exact',purpose:'propose'},argsDigest:'a'.repeat(64),createdAt:Date.now(),expiresAt:Date.now()+60000,state:'PENDING'});
const terminal=(r,s)=>({protocolVersion:1,requestId:r.requestId,terminalState:s,terminalAt:Date.now(),clientSurface:'vcp_chat'});
function setup(t){let now=0;t.mock.method(performance,'now',()=>now);t.mock.timers.enable({apis:['setInterval']});const frames=[],p=createApprovalProtocol((type,data)=>{frames.push({type,data});return true;}),r=request();const snapshot=(active=[r],terms=[])=>({protocolVersion:1,outcome:'SYNCED',serverTime:Date.now(),active,terminal:terms});p.connected(1);p.ingest('tool_approval_snapshot',snapshot(),1);t.after(()=>p.disconnected(p.connectionGeneration.value));return {p,r,frames,snapshot,advance(ms){now+=ms;t.mock.timers.tick(ms);},ack(state=null){p.ingest('tool_approval_ack',{protocolVersion:1,requestId:r.requestId,outcome:'ACCEPTED',terminalState:state,terminalAt:Date.now()},p.connectionGeneration.value);}};}
for(const decision of [true,false])test('ACK timeout means UNKNOWN; late sole current ACK still valid '+decision,t=>{const h=setup(t);h.p.respond(h.r.requestId,decision);h.advance(ACK_WAIT_MS+250);assert.equal(h.p.records.get('one').state,'DELIVERY_UNKNOWN');assert.equal(h.p.records.get('one').acceptedSubmittedDecision,undefined);h.ack();assert.equal(h.p.records.get('one').acceptedSubmittedDecision.decision,decision?'ALLOW':'DENY');assert.equal(h.frames.filter(x=>x.type==='tool_approval_response').length,1);});
test('sync timeout retires generation and old snapshot cannot enable',t=>{const h=setup(t);h.p.connected(2);h.advance(SYNC_WAIT_MS+250);assert(h.p.needsReconnect.value);h.p.ingest('tool_approval_snapshot',h.snapshot(),2);assert.equal(h.p.respond('one',true),false);h.p.connected(3);h.p.ingest('tool_approval_snapshot',h.snapshot(),3);assert(h.p.canRespond(h.p.records.get('one'),true));h.p.ingest('tool_approval_snapshot',h.snapshot([], [terminal(h.r,'DENIED')]),2);assert.equal(h.p.records.get('one').hostTerminal,undefined);});
test('recursive ambiguity never replays in gen1/gen2/gen3',t=>{const h=setup(t);for(let g=1;g<=3;g++){if(g>1){h.p.connected(g);assert.equal(h.p.respond('one',true),false);h.p.ingest('tool_approval_snapshot',h.snapshot(),g);}assert.equal(h.p.respond('one',g%2===1),true);h.advance(ACK_WAIT_MS+250);h.p.ingest('tool_approval_snapshot',h.snapshot(),g);assert.equal(h.p.respond('one',false),false);}assert.equal(h.frames.filter(x=>x.type==='tool_approval_response').length,3);});
for(const decision of [true,false])for(const accepted of [true,false])test('opposite snapshot only conflicts with accepted decision '+decision+'/'+accepted,t=>{const h=setup(t);h.p.respond('one',decision);if(accepted)h.ack();h.p.connected(2);h.p.ingest('tool_approval_snapshot',h.snapshot([], [terminal(h.r,decision?'DENIED':'ALLOWED')]),2);assert.equal(h.p.records.get('one').error,accepted?'PROTOCOL_STATE_CONFLICT':undefined);assert.equal(h.p.records.get('one').hostTerminal,decision?'DENIED':'ALLOWED');});
for(const state of ['ALLOWED','DENIED'])test('local deadline does not manufacture terminal '+state,t=>{const h=setup(t);h.advance(60000);assert.equal(h.p.records.get('one').hostTerminal,undefined);assert.equal(h.p.canRespond(h.p.records.get('one'),true),false);h.p.ingest('tool_approval_terminal',terminal(h.r,state),1);assert.equal(h.p.records.get('one').hostTerminal,state);assert.equal(h.p.records.get('one').error,undefined);});
for(const state of ['ALLOWED','DENIED'])test('terminal before ACK consistent or conflicting '+state,t=>{const h=setup(t);h.p.respond('one',true);h.p.ingest('tool_approval_terminal',terminal(h.r,state),1);assert.equal(h.p.records.get('one').localDecisionAccepted,false);h.ack();assert.equal(h.p.records.get('one').error,state==='DENIED'?'PROTOCOL_STATE_CONFLICT':undefined);});
test('duplicate ACK idempotent, contradictory ACK fails closed',t=>{const h=setup(t);h.p.respond('one',true);h.ack('ALLOWED');const identity=h.p.records.get('one').acceptedSubmittedDecision;h.ack('ALLOWED');assert.deepEqual(h.p.records.get('one').acceptedSubmittedDecision,identity);h.ack('DENIED');assert.equal(h.p.records.get('one').error,'PROTOCOL_STATE_CONFLICT');});
