'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{EventEmitter}=require('node:events');
const {TrustedClientSession,ROOT,WS_PATH}=require('../../modules/trusted-client/trustedClientSession');
const {wrapNative}=require('../../modules/trusted-client/trustedClientKeyProvider');
const {keyIdentity}=require('../../modules/trusted-client/trustedClientIdentityDescriptor');
const P=require('../../modules/trusted-client/protocolProof');
const id=()=>crypto.randomBytes(32).toString('base64url');
const canonical=x=>x===null||typeof x!=='object'?JSON.stringify(x):Array.isArray(x)?'['+x.map(canonical).join(',')+']':'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}';
function fixture({algorithm='ED25519',admission='ADMITTED',delaySign=false}={}){
 const keys=crypto.generateKeyPairSync(algorithm==='ED25519'?'ed25519':'ec',algorithm==='ED25519'?{}:{namedCurve:'prime256v1'});
 const key={publicKeySpki:keys.publicKey.export({type:'spki',format:'der'}).toString('base64url'),providerType:'FIXTURE',providerKeyId:'fixture',publicKeyAlgorithm:algorithm};
 const cid=id(),sid=id(),boot=id(),authority=id(),cap=id(),host='https://fixture.invalid',admin='https://admin.invalid',signed=[],calls=[],sockets=[];let release;
 const descriptor={schemaVersion:1,hostAuthorityId:authority,clientEnrollmentId:cid,...keyIdentity(key.publicKeySpki),providerType:'FIXTURE',providerKeyId:'fixture',implementationProfileId:'vcp_chat.c2'};
 const native={getIdentity:()=>key,readDescriptor:()=>JSON.stringify(descriptor),getSecurityProperties:()=>({productionEligible:false}),signHumanClientProtocolProof:async bytes=>{signed.push(bytes);if(delaySign&&signed.length===3)await new Promise(r=>release=r);return {format:'P1363',bytes:crypto.sign(algorithm==='ED25519'?null:'sha256',bytes,{key:keys.privateKey,dsaEncoding:'ieee-p1363'})};}};
 const proofs=new Map();
 function challenge(purpose,path,extra={}){const fields={protocolVersion:1,purpose,trustedHostOrigin:host,surface:'vcp_chat',hostBootId:boot,hostAuthorityId:authority,publicKeyFingerprint:descriptor.publicKeyFingerprint,method:purpose==='channel-upgrade'?'GET':'POST',path,issuedAt:Date.now(),expiresAt:Date.now()+10000,nonceId:id(),...extra};const d=crypto.createHash('sha256').update(canonical(fields)).digest();const proof={nonceId:fields.nonceId,boundFields:fields,boundFieldDigest:d.toString('hex'),signingInput:Buffer.concat([Buffer.from('VCP-HUMAN-CLIENT\0v1\0'+purpose+'\0'),d]).toString('base64url')};proofs.set(proof.nonceId,proof);return proof;}
 function verify(answer){const c=proofs.get(answer.nonceId);assert(c);assert(P.verifyOutput(key.publicKeySpki,algorithm,Buffer.from(c.signingInput,'base64url'),answer.signature));proofs.delete(answer.nonceId);}
 const fetchImpl=async(url,opt)=>{calls.push({url,opt});assert.equal(opt.redirect,'error');const route=url.slice(host.length),body=JSON.parse(opt.body||'{}');let data;
 if(route===ROOT+'/clients/'+cid+'/session-challenges')data=challenge('session-authenticate',ROOT+'/clients/'+cid+'/sessions',{clientEnrollmentId:cid});
 else if(route===ROOT+'/clients/'+cid+'/sessions'){verify(body);data={clientEnrollmentId:cid,sessionId:sid,currentAdmission:admission,productionAdmission:admission,sessionState:'AUTHENTICATED',expiresAt:Date.now()+60000};}
 else if(route===ROOT+'/sessions/'+sid+'/nonces')data=challenge(body.purpose,ROOT+'/sessions/'+sid+'/'+(body.purpose==='capability-mint'?'capability':'revoke'),{sessionId:sid});
 else if(route===ROOT+'/sessions/'+sid+'/capability'){verify(body);data={capability:cap,websocketUrl:host.replace('https:','wss:')+WS_PATH};}
 else if(route===ROOT+'/sessions/'+sid+'/revoke'){verify(body);data={enrollmentState:'REVOKED'};}else throw Error('Unexpected route');return {ok:true,text:async()=>JSON.stringify(data)};};
 class WS extends EventEmitter{constructor(url,options){super();this.url=url;this.options=options;this.readyState=1;this.frames=[];sockets.push(this);}send(raw){const msg=JSON.parse(raw);if(msg.type==='human_channel_proof')verify(msg.data);this.frames.push(msg);}close(){this.readyState=3;this.emit('close');}}
 const session=new TrustedClientSession({provider:wrapNative(native),hostOrigin:host,adminOrigin:admin,fetchImpl,WebSocketImpl:WS});
 return {session,signed,calls,sockets,release:()=>release?.(),challenge:()=>challenge('channel-upgrade',WS_PATH,{sessionId:sid,capabilityDigest:crypto.createHash('sha256').update(cap).digest('hex')}),ready(ws){ws.emit('message',Buffer.from(JSON.stringify({type:'human_channel_ready',data:{protocolVersion:1,clientSurface:'vcp_chat'}})));},proof(ws){ws.emit('message',Buffer.from(JSON.stringify({type:'human_channel_challenge',data:this.challenge()})));}};
}
const tick=()=>new Promise(r=>setImmediate(r));
for(const algorithm of ['ED25519','ECDSA_P256_SHA256'])test('five-purpose channel contract and plain decision '+algorithm,async()=>{const f=fixture({algorithm});try{await f.session.reconnect();const ws=f.sockets[0];assert.equal(f.session.valid(),false);assert.equal(ws.url,'wss://fixture.invalid'+WS_PATH);assert(ws.options.headers['X-VCP-Human-Capability']);f.proof(ws);await tick();assert.equal(f.session.valid(),false);f.ready(ws);assert(f.session.valid());const before=f.signed.length;f.session.send('tool_approval_response',{requestId:'host-request',approved:true,protocolVersion:1,argsDigest:'a'.repeat(64)},f.session.generation);assert.equal(f.signed.length,before);assert.deepEqual(ws.frames.at(-1).data,{requestId:'host-request',approved:true,protocolVersion:1,argsDigest:'a'.repeat(64)});await f.session.selfRevoke();assert.equal(f.session.enrollment,'REVOKED');assert.equal(f.session.valid(),false);}finally{f.session.disconnect();}});
test('ready before channel proof rejected',async()=>{const f=fixture();await f.session.reconnect();f.ready(f.sockets[0]);assert.equal(f.session.valid(),false);assert.equal(f.sockets[0].readyState,3);f.session.disconnect();});
test('ready while proof signing rejected',async()=>{const f=fixture({delaySign:true});await f.session.reconnect();const ws=f.sockets[0];f.proof(ws);await tick();f.ready(ws);f.release();await tick();assert.equal(f.session.valid(),false);assert.equal(ws.frames.length,0);f.session.disconnect();});
test('production-disabled Host response creates no socket',async()=>{const f=fixture({admission:'DENIED'});await assert.rejects(()=>f.session.reconnect(),/CLIENT_NOT_AUTHORIZED/);assert.equal(f.sockets.length,0);f.session.disconnect();});
test('late old generation proof completion cannot send or revive socket',async()=>{const f=fixture({delaySign:true});await f.session.reconnect();const old=f.sockets[0];f.proof(old);await tick();await f.session.reconnect();f.release();await tick();f.ready(old);assert.equal(old.frames.length,0);assert.equal(f.session.valid(),false);const fresh=f.sockets[1];f.proof(fresh);await tick();f.ready(fresh);assert(f.session.valid());old.emit('close');old.emit('error',Error('old'));assert(f.session.valid());f.session.disconnect();});
test('durable descriptor reconnect uses new capability, not re-enrollment',async()=>{const f=fixture();await f.session.reconnect();const first=f.session.generation;await f.session.reconnect();assert(f.session.generation>first);assert.equal(f.calls.filter(x=>x.url.endsWith('/enrollments')).length,0);assert.equal(f.calls.filter(x=>x.url.endsWith('/capability')).length,2);assert.equal(f.calls.filter(x=>x.url.endsWith('/session-challenges')).length,2);f.session.disconnect();});
