 'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events');
const {TrustedClientNativeService}=require('../../modules/trusted-client/trustedClientNativeService');
const {TrustedDecisionBoundary}=require('../../modules/trusted-client/trustedDecisionBoundary');
const {createApprovalProtocol}=require('../../modules/trusted-client/approvalDelivery');
const {identity}=require('../../modules/trusted-client/humanInputProvenance');
function request(id='request-A',args={command:'grant',projectRoot:'/fixture/O1',purpose:'propose'}){const now=Date.now();return {requestId:id,protocolVersion:1,toolName:'CodexWorker',args,argsDigest:'a'.repeat(64),createdAt:now,expiresAt:now+60000,state:'PENDING'};}
function snap(active=[],terminal=[]){return {protocolVersion:1,outcome:'SYNCED',serverTime:Date.now(),active,terminal};}
function terminal(r,state){return {protocolVersion:1,requestId:r.requestId,terminalState:state,terminalAt:Date.now(),clientSurface:'admin_panel'};}
function harness({attestor,invalidTarget=false}={}){
    const session=new EventEmitter(),power=new EventEmitter(),frames=[],views=[];session.generation=1;session.valid=()=>true;session.status=()=>({enrollment:'ENROLLED',admission:'ADMITTED',session:'AUTHENTICATED'});session.send=(type,data,g,onSend=()=>{})=>{onSend();frames.push({type,data,g});};session.disconnect=()=>session.emit('disconnected',session.generation);
    const wc={};wc.mainFrame={parent:null,url:'file:///trusted/approval.html'};const event={sender:wc,senderFrame:wc.mainFrame};let visible=true,focused=true,lock='UNLOCKED',integrity=true;
    const boundary={generation:1,window:{isVisible:()=>visible,isFocused:()=>focused},open:async()=>{},present:x=>views.push(x),invalidate:()=>{},destroy:()=>{},valid:(e,g)=>e?.sender===wc&&e?.senderFrame===wc.mainFrame&&e.senderFrame.parent===null&&e.senderFrame.url==='file:///trusted/approval.html'&&g===1&&visible&&focused};
    const service=new TrustedClientNativeService({session,boundary,powerMonitor:power,integrity:()=>integrity,lockState:()=>lock,attestor:attestor||{verify:async c=>({kind:'USER_PRESENCE_VERIFIED',context:identity(c),expiresAt:Date.now()+5000})}});
    const r=request('request-A',invalidTarget?{command:'grant',projectRoot:null,purpose:'propose'}:undefined);
    session.emit('connected',1);session.emit('message',{type:'tool_approval_snapshot',data:snap([r])},1);
    return {session,power,frames,views,event,boundary,service,r,setVisible:x=>visible=x,setFocused:x=>focused=x,setLock:x=>lock=x,setIntegrity:x=>integrity=x,
        async present(){assert.equal(await service.presentNext(),true);return views.at(-1).viewGeneration;},close(){service.dispose();}};
}
for(const decision of ['ALLOW','DENY'])test('Main owns exact '+decision+' frame; transport is not acceptance',async()=>{const h=harness();try{const viewGeneration=await h.present();const result=await h.service.submit(h.event,{viewGeneration,decision});assert.equal(result.stage,'SENDING');assert.equal(result.accepted,false);const sent=h.frames.filter(f=>f.type==='tool_approval_response');assert.equal(sent.length,1);assert.deepEqual(sent[0].data,{requestId:h.r.requestId,approved:decision==='ALLOW',protocolVersion:1,argsDigest:h.r.argsDigest});assert.equal(Object.hasOwn(sent[0].data,'signature'),false);await h.service.submit(h.event,{viewGeneration,decision});assert.equal(h.frames.filter(f=>f.type==='tool_approval_response').length,1);}finally{h.close();}});
for(const field of ['requestId','grantId','target','scope','projectRoot','purpose','argsDigest','nonce','clientEnrollmentId','algorithm','bytesToSign','signature'])test('renderer cannot supply '+field,async()=>{const h=harness();try{const viewGeneration=await h.present();await h.service.submit(h.event,{viewGeneration,decision:'ALLOW',[field]:'forged'});assert.equal(h.frames.filter(f=>f.type==='tool_approval_response').length,0);}finally{h.close();}});
for(const attack of ['wrong renderer','iframe','stale frame','wrong URL','hidden','unfocused','stale view'])test('TDB excludes '+attack,async()=>{const h=harness();try{let viewGeneration=await h.present(),event=h.event;if(attack==='wrong renderer')event={...event,sender:{}};if(['iframe','stale frame'].includes(attack))event={...event,senderFrame:{...event.senderFrame,parent:attack==='iframe'?{}:null}};if(attack==='wrong URL')event.senderFrame.url='https://attacker.invalid';if(attack==='hidden')h.setVisible(false);if(attack==='unfocused')h.setFocused(false);if(attack==='stale view')viewGeneration='old';await h.service.submit(event,{viewGeneration,decision:'ALLOW'});assert.equal(h.frames.filter(f=>f.type==='tool_approval_response').length,0);}finally{h.close();}});
for(const decision of ['ALLOW','DENY'])test('safe Deny invalid target '+decision,async()=>{const h=harness({invalidTarget:true});try{const viewGeneration=await h.present();await h.service.submit(h.event,{viewGeneration,decision});assert.equal(h.frames.filter(f=>f.type==='tool_approval_response').length,decision==='DENY'?1:0);}finally{h.close();}});
for(const attack of ['lock','suspend','terminal','generation','destroy','integrity','hidden'])test('async human-presence race '+attack,async()=>{let release;const h=harness({attestor:{verify:c=>new Promise(resolve=>{release=()=>resolve({kind:'USER_PRESENCE_VERIFIED',context:identity(c),expiresAt:Date.now()+5000});})}});try{const viewGeneration=await h.present();const result=h.service.submit(h.event,{viewGeneration,decision:'ALLOW'});if(attack==='lock'){h.setLock('LOCKED');h.power.emit('lock-screen');}if(attack==='suspend')h.power.emit('suspend');if(attack==='terminal')h.session.emit('message',{type:'tool_approval_terminal',data:terminal(h.r,'DENIED')},1);if(attack==='generation'){h.session.generation=2;h.session.emit('connected',2);}if(attack==='destroy')h.service.invalidate();if(attack==='integrity')h.setIntegrity(false);if(attack==='hidden')h.setVisible(false);release();assert.equal((await result).stage,'DISCARDED');assert.equal(h.frames.filter(f=>f.type==='tool_approval_response').length,0);}finally{h.close();}});
test('unproven provenance never sends a frame',async()=>{const h=harness({attestor:{verify:async()=>({kind:'UNPROVEN'})}});try{const viewGeneration=await h.present();await h.service.submit(h.event,{viewGeneration,decision:'ALLOW'});assert.equal(h.frames.filter(f=>f.type==='tool_approval_response').length,0);}finally{h.close();}});
function delivery(){const frames=[];const p=createApprovalProtocol((type,data)=>{frames.push({type,data});return true;});const r=request();p.connected(1);p.ingest('tool_approval_snapshot',snap([r]),1);return {p,r,frames,close(){p.disconnected(p.connectionGeneration.value);}};}
for(const decision of [true,false])test('A2 same-generation retry quarantine '+decision,()=>{const h=delivery();try{h.p.respond(h.r.requestId,decision);h.p.sync();h.p.ingest('tool_approval_snapshot',snap([h.r]),1);assert.equal(h.p.records.get(h.r.requestId).state,'ACTIVE_RETRY_REQUIRES_RECONNECT');assert.equal(h.p.respond(h.r.requestId,!decision),false);assert.equal(h.frames.filter(x=>x.type==='tool_approval_response').length,1);h.p.connected(2);assert.equal(h.p.respond(h.r.requestId,!decision),false);h.p.ingest('tool_approval_snapshot',snap([h.r]),2);assert.equal(h.frames.filter(x=>x.type==='tool_approval_response').length,1);assert.equal(h.p.respond(h.r.requestId,!decision),true);}finally{h.close();}});
for(const decision of [true,false])for(const state of [null,'ALLOWED','DENIED'])test('old generation ACK cannot bind '+decision+'/'+state,()=>{const h=delivery();try{h.p.respond(h.r.requestId,decision);h.p.connected(2);h.p.ingest('tool_approval_snapshot',snap([h.r]),2);h.p.respond(h.r.requestId,!decision);h.p.ingest('tool_approval_ack',{protocolVersion:1,requestId:h.r.requestId,outcome:'ACCEPTED',terminalState:state,terminalAt:Date.now()},1);assert.equal(h.p.records.get(h.r.requestId).acceptedSubmittedDecision,undefined);assert.equal(h.p.records.get(h.r.requestId).error,undefined);}finally{h.close();}});
for(const decision of [true,false])for(const opposite of [true,false])test('A1 null ACK identity '+decision+'/'+opposite,()=>{const h=delivery();try{h.p.respond(h.r.requestId,decision);h.p.ingest('tool_approval_ack',{protocolVersion:1,requestId:h.r.requestId,outcome:'ACCEPTED',terminalState:null},1);const state=(opposite?!decision:decision)?'ALLOWED':'DENIED';h.p.ingest('tool_approval_terminal',terminal(h.r,state),1);const r=h.p.records.get(h.r.requestId);assert.equal(r.acceptedSubmittedDecision.decision,decision?'ALLOW':'DENY');assert.equal(r.hostTerminal,state);assert.equal(r.error,opposite?'PROTOCOL_STATE_CONFLICT':undefined);}finally{h.close();}});
for(const state of ['ALLOWED','DENIED','EXPIRED','CANCELLED','UNKNOWN'])test('fresh sync Host '+state+' not actionable',()=>{const h=delivery();try{h.p.respond(h.r.requestId,true);h.p.connected(2);h.p.ingest('tool_approval_snapshot',snap([],state==='UNKNOWN'?[]:[terminal(h.r,state)]),2);assert.equal(h.p.respond(h.r.requestId,false),false);assert.equal(h.frames.filter(f=>f.type==='tool_approval_response').length,1);assert.equal(h.p.records.get(h.r.requestId).state,state==='UNKNOWN'?'STALE_UNKNOWN':h.p.records.get(h.r.requestId).state);}finally{h.close();}});
test('multi-request rotation makes absent request stale and never replays',()=>{const h=delivery();try{const b=request('request-B');h.p.ingest('tool_approval_request',b,1);h.p.respond(h.r.requestId,true);h.p.connected(2);assert(!h.p.canRespond(h.p.records.get(b.requestId),true));h.p.ingest('tool_approval_snapshot',snap([h.r]),2);assert.equal(h.p.records.get(b.requestId).state,'STALE_UNKNOWN');assert.equal(h.frames.filter(f=>f.type==='tool_approval_response').length,1);}finally{h.close();}});
test('all ACK failures never establish accepted identity',()=>{for(const outcome of ['REQUEST_UNKNOWN','CLIENT_NOT_AUTHORIZED','INVALID_RESPONSE','TARGET_MISMATCH']){const h=delivery();try{h.p.respond(h.r.requestId,true);h.p.ingest('tool_approval_ack',{protocolVersion:1,requestId:h.r.requestId,outcome,terminalState:null},1);assert.equal(h.p.records.get(h.r.requestId).acceptedSubmittedDecision,undefined);}finally{h.close();}}});
test('first send has no async gap after final recheck',async()=>{const h=harness();try{const g=await h.present();let invoked=false;h.session.send=(type,data,gen,onSend=()=>{})=>{if(type==='tool_approval_response'){onSend();invoked=true;queueMicrotask(()=>h.power.emit('lock-screen'));h.frames.push({type,data,gen});}};const r=await h.service.submit(h.event,{viewGeneration:g,decision:'ALLOW'});assert.equal(invoked,true);assert.equal(r.stage,'SENDING');assert.equal(h.frames.filter(f=>f.type==='tool_approval_response').length,1);}finally{h.close();}});
